spring:
  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://i8a105.p.ssafy.io/api/login/oauth2/code/google"
            scope:
              - email
              - profile

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calmwave?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: cos
    password: cos1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        open-in-view: true

  logging.level:
    org.hibernate.SQL: debug

my:
  secret: ${JWT_SECRET_KEY}

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_MYSQL_URL}
    username: ${SPRING_MYSQL_USERNAME}
    password: ${SPRING_MYSQL_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: i8a105.p.ssafy.io
    port: 3092

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  logging.level:
    org.hibernate.SQL: debug

my:
  secret: ${JWT_SECRET_KEY}

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
